In [1]:
# 데이터마이닝

In [2]:
import pandas as pd
import numpy as np

In [4]:
tree = pd.read_csv('covtype.csv')

In [5]:
tree

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,0,3
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,0,3
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,0,3
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,0,3
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,0,3

In [7]:
len(tree.columns)

55

In [8]:
tree.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10',
       'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14',
       'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18',
       'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22',
       'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26',
       'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30',
       'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34',
       'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38',
       'Soil_Type39', 'Soil_Type40', 'Cover_Type'],
      dtype='object')

In [23]:
tree.iloc[0:30,1:16]

,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2
0,51,3,258,0,510,221,232,148,6279,1,0,0,0,0,0
1,56,2,212,-6,390,220,235,151,6225,1,0,0,0,0,0
2,139,9,268,65,3180,234,238,135,6121,1,0,0,0,0,0
3,155,18,242,118,3090,238,238,122,6211,1,0,0,0,0,0
4,45,2,153,-1,391,220,234,150,6172,1,0,0,0,0,0
5,132,6,300,-15,67,230,237,140,6031,1,0,0,0,0,0
6,45,7,270,5,633,222,225,138,6256,1,0,0,0,0,0
7,49,4,234,7,573,222,230,144,6228,1,0,0,0,0,0
8,45,9,240,56,666,223,221,133,6244,1,0,0,0,0,0
9,59,10,247,11,636,228,219,124,6230,1,0,0,0,0,0
10,201,4,180,51,735,218,243,161,6222,1,0,0,0,0,0
11,151,11,371,26,5253,234,240,136,4051,1,0,0,0,0,0
12,134,22,150,69,3215,248,224,92,6091,1,0,0,0,0,0
13,214,7,150,46,771,213,247,170,6211,1,0,0,0,0,0
14,157,4,67,4,674,224,240,151,5600,1,0,0,0,0,0
15,51,7,42,2,752,224,225,137,5576,1,0,0,0,0,0
16,259,1,120,-1,607,216,239,161,6096,1,0,0,0,0,0
17,72,7,85,6,595,228,227,133,5607,1,0,0,0,0,0
18,0,4,95,5,691,214,232,156,5572,1,0,0,0,0,0
19,38,5,85,10,741,220,228,144,5555,1,0,0,0,0,0
20,71,9,60,8,767,230,223,126,5547,1,0,0,0,0,0
21,209,17,216,30,4986,206,253,179,4323,1,0,0,0,0,0
22,114,23,192,82,3339,252,209,71,5972,1,0,0,0,0,0
23,54,8,124,0,638,225,222,130,5569,1,0,0,0,0,0
24,22,9,120,14,732,215,221,143,5534,1,0,0,0,0,0
25,135,6,0,0,860,229,237,142,5494,1,0,0,0,0,0
26,163,10,30,-4,849,230,243,145,5486,1,0,0,0,0,0
27,148,16,323,23,5916,240,236,120,3395,1,0,0,0,0,0
28,135,1,212,30,3670,220,238,154,5643,1,0,0,0,0,0
29,117,24,127,53,3281,253,210,71,6033,1,0,0,0,0,0

In [17]:
tree_soil = tree.iloc[:,14:]
tree_soil

,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
581008,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
581009,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
581010,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
581011,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3

In [19]:
df = pd.DataFrame(tree_soil)

# Soil_Type 열들만 선택 (Cover_Type 제외)
soil_type_columns = [col for col in df.columns if 'Soil_Type' in col]

# 각 Soil_Type 열에서 1의 개수 계산
soil_type_counts = df[soil_type_columns].sum()

print(soil_type_counts)

Soil_Type1       3031
Soil_Type2       7525
Soil_Type3       4823
Soil_Type4      12396
Soil_Type5       1597
Soil_Type6       6575
Soil_Type7        105
Soil_Type8        179
Soil_Type9       1147
Soil_Type10     32634
Soil_Type11     12410
Soil_Type12     29971
Soil_Type13     17431
Soil_Type14       599
Soil_Type15         3
Soil_Type16      2845
Soil_Type17      3422
Soil_Type18      1899
Soil_Type19      4021
Soil_Type20      9259
Soil_Type21       838
Soil_Type22     33373
Soil_Type23     57752
Soil_Type24     21278
Soil_Type25       474
Soil_Type26      2589
Soil_Type27      1086
Soil_Type28       946
Soil_Type29    115247
Soil_Type30     30170
Soil_Type31     25666
Soil_Type32     52519
Soil_Type33     45154
Soil_Type34      1611
Soil_Type35      1891
Soil_Type36       119
Soil_Type37       298
Soil_Type38     15573
Soil_Type39     13806
Soil_Type40      8750
dtype: int64

In [ ]:
custom_row_df = create_custom_row(num_rows, column_counts)
print(custom_row_df)

```

Aspect - 방위각
Slope - 경사도
Horizontal_Distance_To_Hydrology - 물가까지의 수평 거리
Vertical_Distance_To_Hydrology - 물가까지의 수직 거리
Horizontal_Distance_To_Roadways - 도로까지의 수평 거리
Hillshade_9am - 오전 9시 언덕 그늘
Hillshade_Noon - 정오 언덕 그늘
Hillshade_3pm - 오후 3시 언덕 그늘
Horizontal_Distance_To_Fire_Points - 화재 지점까지의 수평 거리
Wilderness_Area1 - 야생지역1
```

In [24]:
# Hillshade 를 직관적으로 봤을 때 평균이 괜찮을수도 있다는 의견과 중앙값이 괜찮을 수 잇따는 의견 숙제시에 hillshade 는 빼기>